# Generated by Django 4.2.28 on 2026-03-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cuisine_type',
            field=models.CharField(choices=[('CHINESE', 'Chinese'), ('MALAY', 'Malay'), ('INDIAN', 'Indian'), ('WESTERN', 'Western'), ('FUSION', 'Fusion'), ('DESSERT', 'Dessert'), ('STREET_FOOD', 'Street Food')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cuisine_types',
            field=models.CharField(choices=[('CHINESE', 'Chinese'), ('MALAY', 'Malay'), ('INDIAN', 'Indian'), ('WESTERN', 'Western'), ('FUSION', 'Fusion'), ('DESSERT', 'Dessert'), ('STREET_FOOD', 'Street Food')], max_length=20),
        ),
    ]
