# Generated by Django 4.2.28 on 2026-03-03 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_listing_cuisine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='closing_time',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AddField(
            model_name='vendor',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
