# Generated by Django 4.2.28 on 2026-03-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='vendors.listing')),
            ],
            options={
                'ordering': ['stop_order'],
            },
        ),
    ]
